backend:
  - changed-files:
      - any-glob-to-any-file: "swapbuds-backend/**/*"

frontend:
  - changed-files:
      - any-glob-to-any-file: "swapbuds-frontend/**/*"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**/*"

ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"

database:
  - changed-files:
      - any-glob-to-any-file: "swapbuds-backend/prisma/**/*"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.spec.ts"
          - "**/*.test.ts"
          - "**/*.e2e.ts"
          - "swapbuds-frontend/e2e/**/*"
          - "swapbuds-backend/test/**/*"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "**/package.json"
          - "**/yarn.lock"
